### ISSUE TITLE
loading modern arena moving_piston blocks

### ISSUE THREAD

**Issue by NotJeven** [Moesh/Calamity#120]
I noticed that the moving_piston blocks are not included in the loading of the modern arena... did you want these in the structure files, as fill commands in ../load_blocks, at all?

**Comment by Moesh** [comment]
I think I've always ran the function manually and then loaded them with the structures. We could certain work it into the load sequence for each arena. I think it could/should be done globally instead of per arena, in that case...

**Comment by NotJeven** [comment]
Are you referring to the functions in /build_protection/setup/?

The moving_piston blocks are going to be different for each arena. I thought it would make sense to include them in the structure blocks but I could write some universal routine with fill commands to place them based on the barrier and entity markers required by the build_protection system.

**Comment by Moesh** [comment]
I honestly thought that's how the system was working currently. I haven't spent enough time in that side of the code base.

I'm happy with either solution. From what I understand, the current solutions are:

1. Load with structure blocks. Level designer bakes in moving_pistons before saving structure, also leaves 1-block gap around. This is how it currently works.
1. Run function when loading blocks. Level designer chooses when to load it, but function runs pretty automatically.
1. Universe function which runs automatically. We could use the vertical marker's horizontal location to determine where to begin. This is because there is nothing stopping creators from moving around in the overworld and even moving the entire arenas.

To me, options 1 or 3 are the most attractive, since it creates a clear sense what happens and when. Either the stuff is baked into the structures or it is handled automatically after the level is loaded. Option 2 feels a bit worse, since there's already quite a lot of things to define. I'd like to keep the level-designer-function-sequencing to a minimum.

**Comment by NotJeven** [comment]
In my opinion option 1 is the best. I'll leave this bug with you to fix then (adding the moving_piston blocks to the structure files). Saves us from having to merge multiple structure file versions.

**Comment by Moesh** [comment]
Alright, I'll leave this as a bug and then handle this when I'm done the updates.

I'm a bit surprised though. I do remember running these when I was saving them...oh well.

**Comment by NotJeven** [comment]
I think everything in /build_protection/setup/ was broken with the barrier block layer moves to y=255... probably a problem to attack on another day

**Comment by Moesh** [comment]
@Vilder50 I think we might either need to axe build_protection or bring it up to date. I think it would probably be best to just make the arena designer place these.

Before we do anything, what do you think?
